### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by adellava** [e-xtrategy/unicam-product-editor#1]
Il benchmarking dovrebbe essere organizzato per categorie:

esempio

- tecnologie abilitanti
- ispirazioni non appartenenti al dominio
- best operating practices

manca poi una comparazione tra i risultati trovati e delle conclusioni

**Comment by paoloandre** [comment]
[Benchmarking](https://github.com/e-xtrategy/unicam-product-editor/blob/master/docs/benchmarking.md) organizzato per categorie. A breve faccio anche le conclusioni. Le comparazioni tra i risultati e le scelte per cui ho optato sono descritte nelle [Iterazioni](https://github.com/e-xtrategy/unicam-product-editor/blob/master/Indice.md). @adellava
